/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.vistas;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;
import presentacion.controles.ControlAdministrarClientes;
import presentacion.controles.ControlAgregarCotizacion;
import presentacion.controles.ControlClientes;
import presentacion.controles.ControlConsultarCotizaciones;
import presentacion.controles.ControlCotizaciones;

/**
 *
 * @author sonic
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private javax.swing.JButton jButtonCotizaciones;
    private javax.swing.JButton jButtonVehiculos;
    private javax.swing.JButton jButtonClientes;

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();

        configurarBotonesMenu();
        setSize(getWidth(), 780);

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEncabezado1 = new presentacion.vistas.PanelEncabezado();
        jPanelMenu = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelEncabezado1, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelEncabezado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonCotizaciones = new javax.swing.JButton();
        jButtonVehiculos = new javax.swing.JButton();
        jButtonClientes = new javax.swing.JButton();

        jPanelMenu.setBackground(new java.awt.Color(240, 242, 245));

        java.awt.GridBagLayout layoutMenu = new java.awt.GridBagLayout();
        jPanelMenu.setLayout(layoutMenu);

        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();

        gbc.insets = new java.awt.Insets(20, 20, 20, 20);
        gbc.anchor = java.awt.GridBagConstraints.CENTER;

        gbc.gridx = 0;
        gbc.gridy = 0;

        jPanelMenu.add(jButtonCotizaciones, gbc);

        gbc.gridx = 1;
        gbc.gridy = 0;

        jPanelMenu.add(jButtonVehiculos, gbc);

        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 2;

        jPanelMenu.add(jButtonClientes, gbc);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelMenu;
    private presentacion.vistas.PanelEncabezado panelEncabezado1;
    // End of variables declaration//GEN-END:variables

    private void configurarBotonMenu(
            javax.swing.JButton boton,
            String texto,
            String rutaIcono,
            Runnable accion
    ) {

        boton.setText("<html><center>" + texto + "</center></html>");
        
        boton.addActionListener(e -> accion.run());

        boton.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 22));
        boton.setForeground(new java.awt.Color(25, 25, 25));

        boton.setBackground(new java.awt.Color(255, 255, 255));
        boton.setFocusPainted(false);
        boton.setBorderPainted(false);
        boton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        boton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        boton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        boton.setVerticalTextPosition(javax.swing.SwingConstants.CENTER);

        boton.setIconTextGap(25);

        boton.setPreferredSize(new java.awt.Dimension(360, 120));

        boton.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(
                        new java.awt.Color(210, 210, 210),
                        1,
                        true
                ),
                javax.swing.BorderFactory.createEmptyBorder(15, 35, 15, 20)
        ));

        javax.swing.ImageIcon iconoOriginal
                = new javax.swing.ImageIcon(getClass().getResource(rutaIcono));

        java.awt.Image imgEscalada
                = iconoOriginal.getImage().getScaledInstance(
                        70,
                        70,
                        java.awt.Image.SCALE_SMOOTH
                );

        boton.setIcon(new javax.swing.ImageIcon(imgEscalada));

        boton.addMouseListener(new java.awt.event.MouseAdapter() {

            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton.setBackground(new java.awt.Color(235, 245, 255));
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton.setBackground(new java.awt.Color(255, 255, 255));
            }
        });
    }

    private void configurarBotonesMenu() {

    configurarBotonMenu(
            jButtonCotizaciones,
            "Administrar<br>Cotizaciones",
            "/cotizacion.png",
            () -> { // Lógica de Cotizaciones
                this.dispose();
                ControlAgregarCotizacion ctrlAgregar = new ControlAgregarCotizacion();
                ControlConsultarCotizaciones ctrlHistorial = new ControlConsultarCotizaciones();
                ControlCotizaciones controlCotizaciones = new ControlCotizaciones(ctrlAgregar, ctrlHistorial);
                ctrlAgregar.setControlCotizaciones(controlCotizaciones);
                ctrlHistorial.setControlCotizaciones(controlCotizaciones);
                controlCotizaciones.administrarCotizaciones();
            }
    );

    configurarBotonMenu(
            jButtonVehiculos,
            "Administrar<br>Vehículos",
            "/automovil.png",
            () -> {
            }
    );

    configurarBotonMenu(
            jButtonClientes,
            "Administrar<br>Clientes",
            "/cliente.png",
            () -> { // Lógica de Clientes
                this.dispose();
                ControlAdministrarClientes ctrlAdminClientes = new ControlAdministrarClientes();
                ControlClientes controlClientes = new ControlClientes(ctrlAdminClientes);
                controlClientes.iniciarModulo();
            }
    );
}
}
