
package presentacion.vistas;

import presentacion.borradores.BorradorCotizacion;
import presentacion.controles.ControlAgregarCotizacion;
import presentacion.interfaces.IControlAgregarCotizacion;
import presentacion.interfaces.vistas.IPruebaAgregarCotizacion;

/**
 *
 * @author romom
 */
public class PruebaAgregarCotizacion extends javax.swing.JFrame implements IPruebaAgregarCotizacion {

    private IControlAgregarCotizacion control;
    /**
     * Creates new form PruebaCotizacion
     */
    public PruebaAgregarCotizacion(IControlAgregarCotizacion control) {
        this.control = control;
        initComponents();
        this.setLocationRelativeTo(null);
        labelEtNumGuardado.setVisible(false);
        labelEtTextoGuardado.setVisible(false);
        
        labelNumGuardado.setVisible(false);
        labelTextoGuardado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmpTxtTextoCot = new javax.swing.JTextField();
        labelTextoCot = new javax.swing.JLabel();
        labelNumCot = new javax.swing.JLabel();
        cmpTxtNumCot = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        labelEtNumGuardado = new javax.swing.JLabel();
        labelNumGuardado = new javax.swing.JLabel();
        labelEtTextoGuardado = new javax.swing.JLabel();
        labelTextoGuardado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmpTxtTextoCot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmpTxtTextoCotActionPerformed(evt);
            }
        });

        labelTextoCot.setText("Texto");

        labelNumCot.setText("Número");

        cmpTxtNumCot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmpTxtNumCotActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        labelEtNumGuardado.setText("Número:");

        labelNumGuardado.setText("_");

        labelEtTextoGuardado.setText("Texto:");

        labelTextoGuardado.setText("_");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(148, 148, 148))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelNumCot)
                            .addComponent(labelTextoCot))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmpTxtTextoCot)
                            .addComponent(cmpTxtNumCot, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelEtTextoGuardado)
                            .addComponent(labelEtNumGuardado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNumGuardado)
                            .addComponent(labelTextoGuardado))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumCot)
                    .addComponent(cmpTxtNumCot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTextoCot)
                    .addComponent(cmpTxtTextoCot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnGuardar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEtNumGuardado)
                    .addComponent(labelNumGuardado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEtTextoGuardado)
                    .addComponent(labelTextoGuardado))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmpTxtTextoCotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmpTxtTextoCotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmpTxtTextoCotActionPerformed

    private void cmpTxtNumCotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmpTxtNumCotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmpTxtNumCotActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        guardarDatos();
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void guardarDatos(){
        
        String numCot = cmpTxtNumCot.getText();
        String textCot = cmpTxtTextoCot.getText();
        
        try{
            int numCotInt = Integer.parseInt(numCot);
            
            control.pruebaBoton(numCotInt, textCot);
            
        } catch(NumberFormatException e){
            System.out.println("Número invalido");
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JTextField cmpTxtNumCot;
    private javax.swing.JTextField cmpTxtTextoCot;
    private javax.swing.JLabel labelEtNumGuardado;
    private javax.swing.JLabel labelEtTextoGuardado;
    private javax.swing.JLabel labelNumCot;
    private javax.swing.JLabel labelNumGuardado;
    private javax.swing.JLabel labelTextoCot;
    private javax.swing.JLabel labelTextoGuardado;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarCotizacionGuardada(BorradorCotizacion borradorCotizacion) {
        
        labelNumGuardado.setText(String.valueOf(borradorCotizacion.getNumero()));
        labelTextoGuardado.setText(borradorCotizacion.getTexto());
        
        labelEtNumGuardado.setVisible(true);
        labelEtTextoGuardado.setVisible(true);
        
        labelNumGuardado.setVisible(true);
        labelTextoGuardado.setVisible(true);
    }

    @Override
    public void mostrar() {
        this.setVisible(true);
    }

    @Override
    public void ocultar() {
        this.setVisible(false);
    }
}
