/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion.vistas;

import dtos.cliente.ClienteDetalleDTO;
import javax.swing.JOptionPane;
import presentacion.borradores.BorradorCliente;
import presentacion.interfaces.IControlAdministrarClientes;
import presentacion.interfaces.vistas.IVistaAgregarEditarCliente;

/**
 *
 * @author romom
 */
public class VistaAgregarEditarCliente extends javax.swing.JFrame implements IVistaAgregarEditarCliente {

    private IControlAdministrarClientes control;

    private boolean modoEdicion = false;

    public VistaAgregarEditarCliente(IControlAdministrarClientes control) {
        initComponents();
        configurarImagen();
        configurarBotones();
        configurarRestriccionesCampos();
        configurarTamanoCampos();

        java.awt.Color colorError = java.awt.Color.RED;
        lblNombre.setForeground(colorError);
        lblPaterno.setForeground(colorError);
        lblMaterno.setForeground(colorError);
        lblTelefono.setForeground(colorError);
        lblCorreo.setForeground(colorError);
        lblNombre.setText(" ");
        lblPaterno.setText(" ");
        lblMaterno.setText(" ");
        lblTelefono.setText(" ");
        lblCorreo.setText(" ");
        configurarValidacionEnTiempoReal();
        this.control = control;
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jButton4 = new javax.swing.JButton();
        panelEncabezado1 = new presentacion.vistas.PanelEncabezado();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblPaterno = new javax.swing.JLabel();
        lblMaterno = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton4.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cliente.png"))); // NOI18N
        jLabel1.setPreferredSize(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Nuevo Cliente");

        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
        jPanel1Layout.rowHeights = new int[] {0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0, 4, 0};
        jPanel1.setLayout(jPanel1Layout);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Apellido Paterno");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 60, 0, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("Apellido Materno");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(40, 0, 0, 0);
        jPanel1.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Teléfono");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 0, 0, 0);
        jPanel1.add(jLabel6, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setText("Correo (opcional)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(40, 60, 0, 0);
        jPanel1.add(jLabel7, gridBagConstraints);

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jTextField1, gridBagConstraints);

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 60, 0, 0);
        jPanel1.add(jTextField2, gridBagConstraints);

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(jTextField3, gridBagConstraints);

        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 60, 0, 0);
        jPanel1.add(jTextField4, gridBagConstraints);

        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jTextField5, gridBagConstraints);

        lblNombre.setBackground(new java.awt.Color(255, 51, 51));
        lblNombre.setText("jLabel8");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        jPanel1.add(lblNombre, gridBagConstraints);

        lblTelefono.setText("jLabel9");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        jPanel1.add(lblTelefono, gridBagConstraints);

        lblCorreo.setText("jLabel10");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
        jPanel1.add(lblCorreo, gridBagConstraints);

        lblPaterno.setText("jLabel11");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
        jPanel1.add(lblPaterno, gridBagConstraints);

        lblMaterno.setText("jLabel12");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        jPanel1.add(lblMaterno, gridBagConstraints);

        jButton5.setBackground(new java.awt.Color(204, 255, 204));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setText("Guardar");
        jButton5.setMaximumSize(new java.awt.Dimension(85, 27));
        jButton5.setMinimumSize(new java.awt.Dimension(85, 27));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 255, 204));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setText("Volver");
        jButton6.setMaximumSize(new java.awt.Dimension(85, 27));
        jButton6.setMinimumSize(new java.awt.Dimension(85, 27));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelEncabezado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelEncabezado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblMaterno;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPaterno;
    private javax.swing.JLabel lblTelefono;
    private presentacion.vistas.PanelEncabezado panelEncabezado1;
    // End of variables declaration//GEN-END:variables

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {
        guardarCliente();
    }

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {
        cancelar();
    }

    private void guardarCliente() {
        String nombre = jTextField1.getText().trim();
        String apPaterno = jTextField2.getText().trim();
        String apMaterno = jTextField5.getText().trim();
        String telefono = jTextField3.getText().trim();
        String correo = jTextField4.getText().trim();

        BorradorCliente borrador = new BorradorCliente(
                null,
                nombre,
                apPaterno,
                apMaterno.isEmpty() ? null : apMaterno,
                telefono,
                correo.isEmpty() ? null : correo
        );

        if (modoEdicion) {
            control.actualizarCliente(borrador);
        } else {
            control.guardarNuevoCliente(borrador);
        }
    }

    private void cancelar() {
        control.cancelarAgregarEditar();
    }

    @Override
    public void cargarDatosCliente(ClienteDetalleDTO cliente) {
        modoEdicion = true;
        jLabel2.setText("Editar Cliente");

        jTextField1.setText(cliente.getNombre());
        jTextField2.setText(cliente.getApellidoPaterno());
        jTextField5.setText(cliente.getApellidoMaterno() != null ? cliente.getApellidoMaterno() : "");
        jTextField3.setText(cliente.getTelefono() != null ? cliente.getTelefono() : "");
        jTextField4.setText(cliente.getCorreo() != null ? cliente.getCorreo() : "");
    }

    @Override
    public void limpiarFormulario() {
        modoEdicion = false;
        jLabel2.setText("Nuevo Cliente");

        jTextField1.setText("");
        jTextField2.setText("");
        jTextField5.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
    }

    @Override
    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(
                this,
                mensaje,
                "Aviso",
                JOptionPane.WARNING_MESSAGE
        );
    }

    @Override
    public void mostrarMensajeExito(String mensaje) {
        JOptionPane.showMessageDialog(
                this,
                mensaje,
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE
        );
    }

    @Override
    public void mostrar() {
        setVisible(true);
    }

    @Override
    public void ocultar() {
        dispose();
    }

    private void configurarImagen() {
        java.awt.Image imagen = new javax.swing.ImageIcon(
                getClass().getResource("/cliente.png")
        ).getImage();

        java.awt.Image imagenEscalada = imagen.getScaledInstance(
                180,
                180,
                java.awt.Image.SCALE_SMOOTH
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(imagenEscalada));
    }

    private void configurarBotones() {
        jButton6.addActionListener(e -> {
            cancelar();
        });

        jButton5.addActionListener(e -> {
            guardarCliente();
        });
    }

    private void configurarValidacionEnTiempoReal() {
        javax.swing.event.DocumentListener docListener = new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                validarCampos();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                validarCampos();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                validarCampos();
            }
        };

        jTextField1.getDocument().addDocumentListener(docListener);
        jTextField2.getDocument().addDocumentListener(docListener);
        jTextField3.getDocument().addDocumentListener(docListener);
        jTextField4.getDocument().addDocumentListener(docListener);
        jTextField5.getDocument().addDocumentListener(docListener);

        validarCampos();
    }

    private void validarCampos() {
        String nombre = jTextField1.getText().trim();
        String apPaterno = jTextField2.getText().trim();
        String apMaterno = jTextField5.getText().trim();
        String telefono = jTextField3.getText().trim();
        String correo = jTextField4.getText().trim();

        String regexLetras = "^[a-zA-ZáéíóúÁÉÍÓÚñÑüÜ\\s]+$";
        String regexCorreo = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$";

        boolean formularioValido = true;

        lblNombre.setText(" ");
        lblPaterno.setText(" ");
        lblMaterno.setText(" ");
        lblTelefono.setText(" ");
        lblCorreo.setText(" ");

        if (nombre.isEmpty()) {
            lblNombre.setText("El nombre es obligatorio.");
            formularioValido = false;
        } else if (!nombre.matches(regexLetras)) {
            lblNombre.setText("Solo letras permitidas.");
            formularioValido = false;
        } else if (nombre.length() > 20) {
            lblNombre.setText("Máximo 20 caracteres.");
            formularioValido = false;
        }

        if (apPaterno.isEmpty()) {
            lblPaterno.setText("El apellido es obligatorio.");
            formularioValido = false;
        } else if (!apPaterno.matches(regexLetras)) {
            lblPaterno.setText("Solo letras permitidas.");
            formularioValido = false;
        } else if (apPaterno.length() > 20) {
            lblPaterno.setText("Máximo 20 caracteres.");
            formularioValido = false;
        }

        if (!apMaterno.isEmpty()) {
            if (!apMaterno.matches(regexLetras)) {
                lblMaterno.setText("Solo letras permitidas.");
                formularioValido = false;
            } else if (apMaterno.length() > 20) {
                lblMaterno.setText("Máximo 20 caracteres.");
                formularioValido = false;
            }
        }

        if (telefono.isEmpty()) {
            lblTelefono.setText("El teléfono es obligatorio.");
            formularioValido = false;
        } else if (!telefono.matches("^\\d{10}$")) {
            lblTelefono.setText("Debe tener 10 dígitos.");
            formularioValido = false;
        }

        if (!correo.isEmpty() && !correo.matches(regexCorreo)) {
            lblCorreo.setText("Formato de correo inválido.");
            formularioValido = false;
        }

        jButton5.setEnabled(formularioValido);
    }

    private void configurarRestriccionesCampos() {

        limitarCampoTexto(jTextField1, 20, true);
        limitarCampoTexto(jTextField2, 20, true);
        limitarCampoTexto(jTextField5, 20, true);
        limitarCampoTexto(jTextField4, 40, false);

        limitarCampoTelefono(jTextField3);
    }

    private void limitarCampoTexto(javax.swing.JTextField campo, int maxCaracteres, boolean soloLetras) {

        ((javax.swing.text.AbstractDocument) campo.getDocument())
                .setDocumentFilter(new javax.swing.text.DocumentFilter() {

                    @Override
                    public void replace(FilterBypass fb, int offset, int length,
                            String text, javax.swing.text.AttributeSet attrs)
                            throws javax.swing.text.BadLocationException {

                        if (text == null) {
                            return;
                        }

                        String textoActual = fb.getDocument().getText(
                                0,
                                fb.getDocument().getLength()
                        );

                        String nuevoTexto = textoActual.substring(0, offset)
                                + text
                                + textoActual.substring(offset + length);

                        if (nuevoTexto.length() > maxCaracteres) {
                            return;
                        }

                        if (soloLetras
                                && !text.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑüÜ\\s]*")) {
                            return;
                        }

                        super.replace(fb, offset, length, text, attrs);
                    }

                    @Override
                    public void insertString(FilterBypass fb, int offset,
                            String string,
                            javax.swing.text.AttributeSet attr)
                            throws javax.swing.text.BadLocationException {

                        replace(fb, offset, 0, string, attr);
                    }
                });
    }

    private void limitarCampoTelefono(javax.swing.JTextField campo) {

        ((javax.swing.text.AbstractDocument) campo.getDocument())
                .setDocumentFilter(new javax.swing.text.DocumentFilter() {

                    @Override
                    public void replace(FilterBypass fb, int offset, int length,
                            String text, javax.swing.text.AttributeSet attrs)
                            throws javax.swing.text.BadLocationException {

                        if (text == null) {
                            return;
                        }

                        String textoActual = fb.getDocument().getText(
                                0,
                                fb.getDocument().getLength()
                        );

                        String nuevoTexto = textoActual.substring(0, offset)
                                + text
                                + textoActual.substring(offset + length);

                        if (nuevoTexto.length() > 10) {
                            return;
                        }

                        if (!text.matches("\\d*")) {
                            return;
                        }

                        super.replace(fb, offset, length, text, attrs);
                    }

                    @Override
                    public void insertString(FilterBypass fb, int offset,
                            String string,
                            javax.swing.text.AttributeSet attr)
                            throws javax.swing.text.BadLocationException {

                        replace(fb, offset, 0, string, attr);
                    }
                });
    }

    private void configurarTamanoCampos() {

        java.awt.Dimension tamanoCampo = new java.awt.Dimension(260, 40);

        jTextField1.setPreferredSize(tamanoCampo);
        jTextField2.setPreferredSize(tamanoCampo);
        jTextField3.setPreferredSize(tamanoCampo);
        jTextField4.setPreferredSize(tamanoCampo);
        jTextField5.setPreferredSize(tamanoCampo);
    }

}
