package presentacion.vistas;

import javax.swing.JOptionPane;
import presentacion.interfaces.IControlClientes;
import presentacion.interfaces.vistas.IVistaPrincipalClientes;

/**
 *
 * @author sonic
 */
public class VistaPrincipalClientes extends javax.swing.JFrame implements IVistaPrincipalClientes {

    private IControlClientes control;

    /**
     * Creates new form VistaPrincipalClientes
     */
    public VistaPrincipalClientes(IControlClientes control) {
        initComponents();
        this.control = control;

        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelEncabezado1 = new presentacion.vistas.PanelEncabezado();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnVerTodas = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1110, 700));

        getContentPane().add(panelEncabezado1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Clientes");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 52, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        btnNuevo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 550, 45, 550);
        jPanel1.add(btnNuevo, gridBagConstraints);

        btnVerTodas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVerTodas.setText("Ver todos");
        btnVerTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerTodasActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 550, 95, 550);
        jPanel1.add(btnVerTodas, gridBagConstraints);

        btnVolver.setBackground(new java.awt.Color(255, 255, 204));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(btnVolver, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {
        crearCliente();
    }

    private void btnVerTodasActionPerformed(java.awt.event.ActionEvent evt) {
        administrarClientes();
    }

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {
        volver();
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnVerTodas;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private presentacion.vistas.PanelEncabezado panelEncabezado1;
    // End of variables declaration

    private void crearCliente() {
        this.ocultar();
        control.crearCliente();
    }

    private void administrarClientes() {
        this.ocultar();
        control.administrarClientes();
    }

    private void volver() {
        this.ocultar();
        control.volver();
    }

    @Override
    public void mostrar() {
        this.setVisible(true);
    }

    @Override
    public void ocultar() {
        this.dispose();
    }

    @Override
    public void mostrarMensaje(String mensajeError) {
        JOptionPane.showMessageDialog(
                this,
                mensajeError,
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }
}