
package presentacion.vistas;

import dtos.servicio.ServicioDetalleDTO;
import insumoservicio.InsumoServicioDetalleDTO;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.io.File;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import presentacion.borradores.BorradorCotizacion;
import presentacion.borradores.BorradorInsumoCotizacion;
import presentacion.interfaces.IControlAgregarCotizacion;
import presentacion.interfaces.vistas.IVistaCrearCotizacion;
import presentacion.utils.GeneradorPDF;

/**
 *
 * @author romom
 */
public class VistaCrearCotizacion extends JFrame implements IVistaCrearCotizacion{

    private IControlAgregarCotizacion control;
    /**
     * Creates new form VistaCrearCotizacion
     */
    public VistaCrearCotizacion(IControlAgregarCotizacion control) {
        initComponents();
        configurarTablaInsumos();
        
        this.control = control;
        
        setLocationRelativeTo(null);
    }
    
    private void configurarTablaInsumos(){

        tblInsumosServicio.setRowHeight(30);
        tblInsumosServicio.setShowGrid(true);
        tblInsumosServicio.setGridColor(java.awt.Color.BLACK);
        tblInsumosServicio.setFont(new Font("Segoe UI", Font.BOLD, 14));

        JTableHeader header = tblInsumosServicio.getTableHeader();
        header.setFont(new Font("Segoe UI", Font.BOLD, 14)); 
        header.setBackground(new Color(200, 200, 200));
        header.setForeground(Color.BLACK);
        header.setOpaque(false);
        
        header.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        header.setReorderingAllowed(false);


        DefaultTableCellRenderer rendererPersonalizado = new DefaultTableCellRenderer() {

            Color colorAzulClaro = new Color(218, 235, 255);
            Color colorBlanco = Color.WHITE;

            @Override
            public Component getTableCellRendererComponent(
                    JTable table, 
                    Object value,
                    boolean isSelected,
                    boolean hasFocus,
                    int row, 
                    int column) {

                Component celda = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                if (!isSelected) {
                    if (row % 2 == 0) {
                        celda.setBackground(colorAzulClaro);
                    } else {
                        celda.setBackground(colorBlanco);
                    }
                }

                setBorder(BorderFactory.createEmptyBorder(0, 10, 0, 0));

                return celda;
            }
            
        };

        tblInsumosServicio.setDefaultRenderer(Object.class, rendererPersonalizado);
        tblInsumosServicio.setDefaultRenderer(Integer.class, rendererPersonalizado);
        tblInsumosServicio.setDefaultRenderer(String.class, rendererPersonalizado);
        tblInsumosServicio.setDefaultRenderer(java.math.BigDecimal.class, rendererPersonalizado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel8 = new javax.swing.JPanel();
        panelEncabezado1 = new presentacion.vistas.PanelEncabezado();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblNombreServicio = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInsumosServicio = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cmpTxtTotalInsumos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmpTxtCostoManoObra = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 700));
        setPreferredSize(new java.awt.Dimension(1000, 700));
        getContentPane().add(panelEncabezado1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(204, 255, 51));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Nueva Cotización");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 25, 0, 0);
        jPanel2.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText(" - ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        jPanel2.add(jLabel2, gridBagConstraints);

        lblNombreServicio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNombreServicio.setText("jLabel3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(lblNombreServicio, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jPanel2, gridBagConstraints);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 204));
        jPanel6.setLayout(new java.awt.BorderLayout());

        tblInsumosServicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No.", "Insumo", "Costo", "Cantidad", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblInsumosServicio);
        if (tblInsumosServicio.getColumnModel().getColumnCount() > 0) {
            tblInsumosServicio.getColumnModel().getColumn(0).setHeaderValue("No.");
            tblInsumosServicio.getColumnModel().getColumn(1).setHeaderValue("Insumo");
            tblInsumosServicio.getColumnModel().getColumn(2).setHeaderValue("Costo");
            tblInsumosServicio.getColumnModel().getColumn(3).setHeaderValue("Cantidad");
            tblInsumosServicio.getColumnModel().getColumn(4).setHeaderValue("Subtotal");
        }

        jPanel6.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(25, 25, 25, 25);
        jPanel3.add(jPanel6, gridBagConstraints);

        jPanel7.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Total insumos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 111;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 0);
        jPanel7.add(jLabel3, gridBagConstraints);

        cmpTxtTotalInsumos.setEditable(false);
        cmpTxtTotalInsumos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmpTxtTotalInsumos.setText("jTextField1");
        cmpTxtTotalInsumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmpTxtTotalInsumosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 55);
        jPanel7.add(cmpTxtTotalInsumos, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Mano de obra(Nivel)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 21, 0, 25);
        jPanel7.add(jLabel4, gridBagConstraints);

        cmpTxtCostoManoObra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmpTxtCostoManoObra.setText("jTextField2");
        cmpTxtCostoManoObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmpTxtCostoManoObraActionPerformed(evt);
            }
        });
        cmpTxtCostoManoObra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmpTxtCostoManoObraKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 55);
        jPanel7.add(cmpTxtCostoManoObra, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("TOTAL:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 25, 0, 0);
        jPanel7.add(jLabel5, gridBagConstraints);

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotal.setText(" jLabel6");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        jPanel7.add(lblTotal, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel3.add(jPanel7, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jPanel3, gridBagConstraints);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 60, 20, 60));
        jPanel4.setLayout(new java.awt.BorderLayout());

        btnAceptar.setText("Aceptar y Descargar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel4.add(btnAceptar, java.awt.BorderLayout.LINE_END);

        jPanel5.setLayout(new java.awt.GridBagLayout());

        btnVolver.setText("Volver");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel5.add(btnVolver, gridBagConstraints);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 55, 0, 0);
        jPanel5.add(btnCancelar, gridBagConstraints);

        jPanel4.add(jPanel5, java.awt.BorderLayout.LINE_START);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(jPanel4, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        crearCotizacion();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cmpTxtTotalInsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmpTxtTotalInsumosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmpTxtTotalInsumosActionPerformed

    private void cmpTxtCostoManoObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmpTxtCostoManoObraActionPerformed
        actualizarCostoManoObra();
    }//GEN-LAST:event_cmpTxtCostoManoObraActionPerformed

    private void cmpTxtCostoManoObraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmpTxtCostoManoObraKeyReleased
        actualizarCostoManoObra();
    }//GEN-LAST:event_cmpTxtCostoManoObraKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JTextField cmpTxtCostoManoObra;
    private javax.swing.JTextField cmpTxtTotalInsumos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombreServicio;
    private javax.swing.JLabel lblTotal;
    private presentacion.vistas.PanelEncabezado panelEncabezado1;
    private javax.swing.JTable tblInsumosServicio;
    // End of variables declaration//GEN-END:variables

    @Override
    public void cargarServicioSeleccionado(ServicioDetalleDTO servicio) {
        
        lblNombreServicio.setText(servicio.getNombre());
        cmpTxtCostoManoObra.setText(servicio.getPrecioManoObraSugerido().toString());
        llenarTablaInsumos(servicio);
        recalcularTotales();
        
    }
    
    private void llenarTablaInsumos(ServicioDetalleDTO servicio){
        
        String[] columnas = {"No.", "Insumo", "Costo", "Cantidad", "Subtotal", "ID_INSUMO"};

        DefaultTableModel modeloTabla = new DefaultTableModel(columnas, 0) {


            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 2 || column == 3; 
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                switch (columnIndex) {
                    case 0: return Integer.class;
                    case 1: return String.class;
                    case 2: return BigDecimal.class;
                    case 3: return Integer.class;
                    case 4: return BigDecimal.class;
                    case 5: return Long.class;
                    default: return Object.class;
                }
            }
        };
        
        int numeroInsumoServicio = 1;
        for(InsumoServicioDetalleDTO insumoServicio: servicio.getInsumosServicio()){
            
            BigDecimal costoInsumo = insumoServicio.getInsumo().getPrecioSugerido();
            String nombreInsumo = insumoServicio.getInsumo().getNombre();
            int cantidad = insumoServicio.getCantidadDefault();
            BigDecimal subtotal = insumoServicio.getSubtotal();
            
            Long idInsumo = insumoServicio.getInsumo().getId();
            
            modeloTabla.addRow(
                    new Object[]{
                        numeroInsumoServicio,
                        nombreInsumo,
                        costoInsumo,
                        cantidad,
                        subtotal,
                        idInsumo
                    }
            );
            
            numeroInsumoServicio++;
            
        }
        
        tblInsumosServicio.setModel(modeloTabla);
        
        tblInsumosServicio.removeColumn(tblInsumosServicio.getColumnModel().getColumn(5));
        
        modeloTabla.addTableModelListener(new TableModelListener() {
    
            @Override
            public void tableChanged(TableModelEvent e) {

                if (e.getType() == javax.swing.event.TableModelEvent.UPDATE) {

                    int filaModificada = e.getFirstRow();
                    int columnaModificada = e.getColumn();

                    if (columnaModificada == 2 || columnaModificada == 3) {

                        try {
                            Object valorCosto = modeloTabla.getValueAt(filaModificada, 2);
                            Object valorCantidad = modeloTabla.getValueAt(filaModificada, 3);

                            if (valorCosto == null || valorCantidad == null) return;

                            BigDecimal costo = new BigDecimal(valorCosto.toString()).setScale(2, java.math.RoundingMode.HALF_UP);
                            Integer cantidad = Integer.valueOf(valorCantidad.toString());

                            BigDecimal nuevoSubtotal = costo.multiply(BigDecimal.valueOf(cantidad)).setScale(2, java.math.RoundingMode.HALF_UP);

                            javax.swing.SwingUtilities.invokeLater(() -> {

                                if (!valorCosto.toString().equals(costo.toString())) {
                                    modeloTabla.setValueAt(costo, filaModificada, 2);
                                }

                                modeloTabla.setValueAt(nuevoSubtotal, filaModificada, 4);
                                
                                recalcularTotales();
                                
                                crearBorradorCotizacion();
                            });

                        } catch (NumberFormatException ex) {}
                    }
                }
            }
        });
        
      
    }
    
    private void recalcularTotales() {

        DefaultTableModel modelo = (DefaultTableModel) tblInsumosServicio.getModel();
        BigDecimal sumaInsumos = BigDecimal.ZERO;

        for (int i = 0; i < modelo.getRowCount(); i++) {
            Object valorSubtotal = modelo.getValueAt(i, 4);
            if (valorSubtotal != null) {
                BigDecimal subtotalFila = new BigDecimal(valorSubtotal.toString());
                sumaInsumos = sumaInsumos.add(subtotalFila);
            }
        }

        cmpTxtTotalInsumos.setText(sumaInsumos.setScale(2, java.math.RoundingMode.HALF_UP).toString());

        BigDecimal costoManoObra = BigDecimal.ZERO;
        try {
            String textoManoObra = cmpTxtCostoManoObra.getText();
            if (!textoManoObra.trim().isEmpty()) {
                costoManoObra = new BigDecimal(textoManoObra);
            }
        } catch (NumberFormatException e) {}

        BigDecimal totalGeneral = sumaInsumos.add(costoManoObra);

        lblTotal.setText(totalGeneral.setScale(2, java.math.RoundingMode.HALF_UP).toString());
    }
    
    private void actualizarCostoManoObra(){
        recalcularTotales();
        crearBorradorCotizacion();
    }
    
    private void crearBorradorCotizacion(){
        
        String totalInsumosS = cmpTxtTotalInsumos.getText();
        String costoManoObraS = cmpTxtCostoManoObra.getText();
        String totalS = lblTotal.getText();
        
        Double totalInsumosD = null;
        Double costoManoObraD = null;
        Double totalD = null;
        try{
            totalInsumosD = Double.valueOf(totalInsumosS);
            costoManoObraD = Double.valueOf(costoManoObraS);
            totalD = Double.valueOf(totalS);
            
        } catch(NumberFormatException e){}
        
        if(totalInsumosD != null && costoManoObraD != null && totalD != null){
            
            BigDecimal totalInsumos = BigDecimal.valueOf(totalInsumosD);
            BigDecimal costoManoObra = BigDecimal.valueOf(costoManoObraD);
            BigDecimal total = BigDecimal.valueOf(totalD);
            
            List<BorradorInsumoCotizacion> borradoresInsumoCotizacion = obtenerInsumosCotizacion();
            
            BorradorCotizacion borradorCotizacion = new BorradorCotizacion(totalInsumos, costoManoObra, total, borradoresInsumoCotizacion);
         
            control.guardarCambioCotizacion(borradorCotizacion);
            
        }

    }
    
    private List<BorradorInsumoCotizacion> obtenerInsumosCotizacion(){
        
        List<BorradorInsumoCotizacion> borradoresInsumoCotizacion = new ArrayList<>();

        DefaultTableModel modelo = (DefaultTableModel) tblInsumosServicio.getModel();

        for (int i = 0; i < modelo.getRowCount(); i++) {

            String nombre = modelo.getValueAt(i, 1).toString();

            BigDecimal costo = new BigDecimal(modelo.getValueAt(i, 2).toString());
            Integer cantidad = Integer.valueOf(modelo.getValueAt(i, 3).toString());
            BigDecimal subtotal = new BigDecimal(modelo.getValueAt(i, 4).toString());
            Long idInsumo = Long.valueOf(modelo.getValueAt(i, 5).toString());

            BorradorInsumoCotizacion borrador = new BorradorInsumoCotizacion(nombre, cantidad, costo, subtotal, idInsumo);

            borradoresInsumoCotizacion.add(borrador);
        }
        
        return borradoresInsumoCotizacion;
    }
    
    
    private void crearCotizacion(){
        crearBorradorCotizacion();
        control.crearCotizacion();
    }

    @Override
    public void mostrar() {
        setVisible(true);
    }

    @Override
    public void ocultar() {
        dispose();
    }

    @Override
    public void mostrarGuardadoPdf() {
        
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Guardar Cotización en PDF");
        fileChooser.setSelectedFile(new File("Cotizacion_" + System.currentTimeMillis() + ".pdf")); 

        int seleccion = fileChooser.showSaveDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File archivoDestino = fileChooser.getSelectedFile();
            String rutaGuardado = archivoDestino.getAbsolutePath();

            if (!rutaGuardado.toLowerCase().endsWith(".pdf")) {
                rutaGuardado += ".pdf";
            }
            GeneradorPDF.crearDocumentoPDF(rutaGuardado);

            javax.swing.JOptionPane.showMessageDialog(this, "¡PDF generado con éxito en:\n" + rutaGuardado);
        }
    }
    
    @Override
    public void mostrarError(String mensajeError) {
        JOptionPane.showMessageDialog(this, mensajeError, "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }

}
